### ISSUE TITLE
bug: extra parameters in url are lost when data comes

### ISSUE THREAD

**Issue by ssibrahimbas** [acikkaynak/deprem-yardim-frontend#752]
## Bug Definition
I just clicked on the link while reviewing an issue. There was an id parameter in this link and the url was updated when the data came from the api. id value removed from url.

-- Please add discord contact information
** discord username: @ss.ibrahimbas#4990 **

## Bug environment
Describe the environment produces the bug. For example:
Both:
- rc.afetharita.com
- afetharita.com
## Describe how you are producing the bug step by step

1. Go to '[this link](https://afetharita.com/en?lat=36.936358468543396&lng=36.570053100585945&zoom=12&id=756628)'
2. look the url
3. &id field is going

## Expected Behaviour
id field is should stay in the url

## Screen shots
If possible, add screenshots to describe your bug.

## Desktop Information
- Operating System: [Windows 11]
- Browser [chrome]
- Version [for example 22]

## Additional Context
Not have additional context

**Comment by buraktuzlutas** [comment]
The problem has been resolved. Even if the page is refreshed, the id is displayed.thanks

**Comment by cemiluzunhasan** [comment]
Out of curiosity, where was the problem? I was looking at the issues and this thing which would interest me @buraktuzlutas

**Comment by buraktuzlutas** [comment]
When you refresh the page from the link https://afetharita.com/en?lng=36.570053100585945&lat=36.936358468543396&zoom=12&id=756628, the id information was corrected, while https://rc.afetharita.com/, the id information disappeared when the page was refreshed. @cemiluzunhasan

**Comment by cemiluzunhasan** [comment]
I was asking about the implementation but np anyway if it has been solved. Thanks @buraktuzlutas

**Comment by ssibrahimbas** [comment]
I see the problem persists in rc and production. It hasn't made it to rc yet or could it be an overlooked point? @buraktuzlutas

**Comment by CyhnYldz** [comment]
Hi.
Issue #760 is vise versa of this issue so which path should we follow on this. should id stay on URL or not

**Comment by CyhnYldz** [comment]
the id stay's in URL until you move the map or refresh the page as expected. but if you want to copy and paste URL to share the marker the id vanishes from URL

**Comment by fdemir** [comment]
expected behaviour. closd this issue.

**Comment by Rayberk** [comment]
me and @cemiluzunhasan are right now in this issue pr wip

**Comment by cemiluzunhasan** [comment]
Solved and created the related PR
